// <auto-generated />
using System;
using InsideAirBnBV5.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace InsideAirBnBV5.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20190510193156_REmovedLicence")]
    partial class REmovedLicence
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0-preview5.19227.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("InsideAirBnBV5.Models.Calendar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Available");

                    b.Property<DateTime>("Date");

                    b.Property<int>("ListingId");

                    b.Property<string>("Price");

                    b.Property<string>("TestString");

                    b.HasKey("Id");

                    b.HasIndex("ListingId");

                    b.ToTable("Calendar");
                });

            modelBuilder.Entity("InsideAirBnBV5.Models.Listings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Access");

                    b.Property<int?>("Accommodates");

                    b.Property<string>("Amenities");

                    b.Property<int?>("Availability30");

                    b.Property<int?>("Availability365");

                    b.Property<int?>("Availability60");

                    b.Property<int?>("Availability90");

                    b.Property<double?>("Bathrooms");

                    b.Property<string>("BedType");

                    b.Property<int?>("Bedrooms");

                    b.Property<int?>("Beds");

                    b.Property<int>("CalculatedHostListingsCount");

                    b.Property<DateTime?>("CalendarLastScraped");

                    b.Property<string>("CalendarUpdated");

                    b.Property<string>("CancellationPolicy");

                    b.Property<string>("City");

                    b.Property<string>("CleaningFee");

                    b.Property<string>("Country");

                    b.Property<string>("CountryCode");

                    b.Property<string>("Description");

                    b.Property<string>("ExperiencesOffered");

                    b.Property<string>("ExtraPeople");

                    b.Property<DateTime?>("FirstReview");

                    b.Property<int?>("GuestsIncluded");

                    b.Property<string>("HasAvailability");

                    b.Property<string>("HostAbout");

                    b.Property<string>("HostAcceptanceRate");

                    b.Property<string>("HostHasProfilePic");

                    b.Property<int>("HostId");

                    b.Property<string>("HostIdentityVerified");

                    b.Property<string>("HostIsSuperhost");

                    b.Property<int?>("HostListingsCount");

                    b.Property<string>("HostLocation");

                    b.Property<string>("HostName");

                    b.Property<string>("HostNeighbourhood");

                    b.Property<string>("HostPictureUrl");

                    b.Property<string>("HostResponseRate");

                    b.Property<string>("HostResponseTime");

                    b.Property<DateTime?>("HostSince");

                    b.Property<string>("HostThumbnailUrl");

                    b.Property<int?>("HostTotalListingsCount");

                    b.Property<string>("HostUrl");

                    b.Property<string>("HostVerifications");

                    b.Property<string>("HouseRules");

                    b.Property<string>("InstantBookable");

                    b.Property<string>("Interaction");

                    b.Property<string>("IsBusinessTravelReady");

                    b.Property<string>("IsLocationExact");

                    b.Property<string>("JurisdictionNames");

                    b.Property<DateTime?>("LastReview");

                    b.Property<DateTime>("LastScraped");

                    b.Property<double?>("Latitude");

                    b.Property<string>("ListingUrl");

                    b.Property<double?>("Longitude");

                    b.Property<string>("Market");

                    b.Property<int?>("MaximumNights");

                    b.Property<string>("MediumUrl");

                    b.Property<int?>("MinimumNights");

                    b.Property<string>("MonthlyPrice");

                    b.Property<string>("Name");

                    b.Property<string>("NeighborhoodOverview");

                    b.Property<string>("Neighbourhood");

                    b.Property<string>("NeighbourhoodCleansed");

                    b.Property<string>("NeighbourhoodGroupCleansed");

                    b.Property<string>("Notes");

                    b.Property<int?>("NumberOfReviews");

                    b.Property<string>("PictureUrl");

                    b.Property<string>("Price");

                    b.Property<string>("PropertyType");

                    b.Property<string>("RequireGuestPhoneVerification");

                    b.Property<string>("RequireGuestProfilePicture");

                    b.Property<string>("RequiresLicense");

                    b.Property<int?>("ReviewScoresAccuracy");

                    b.Property<int?>("ReviewScoresCheckin");

                    b.Property<int?>("ReviewScoresCleanliness");

                    b.Property<int?>("ReviewScoresCommunication");

                    b.Property<int?>("ReviewScoresLocation");

                    b.Property<int?>("ReviewScoresRating");

                    b.Property<int?>("ReviewScoresValue");

                    b.Property<double?>("ReviewsPerMonth");

                    b.Property<string>("RoomType");

                    b.Property<double>("ScrapeId");

                    b.Property<string>("SecurityDeposit");

                    b.Property<string>("SmartLocation");

                    b.Property<string>("Space");

                    b.Property<string>("SquareFeet");

                    b.Property<string>("State");

                    b.Property<string>("Street");

                    b.Property<string>("Summary");

                    b.Property<string>("ThumbnailUrl");

                    b.Property<string>("Transit");

                    b.Property<string>("WeeklyPrice");

                    b.Property<string>("XlPictureUrl");

                    b.Property<string>("Zipcode");

                    b.HasKey("Id");

                    b.ToTable("Listings");
                });

            modelBuilder.Entity("InsideAirBnBV5.Models.Neighbourhoods", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Neighbourhood");

                    b.HasKey("Id");

                    b.ToTable("Neighbourhoods");
                });

            modelBuilder.Entity("InsideAirBnBV5.Models.Reviews", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Comments");

                    b.Property<DateTime>("Date");

                    b.Property<int>("ListingId");

                    b.Property<int>("ReviewerId");

                    b.Property<string>("ReviewerName");

                    b.HasKey("Id");

                    b.HasIndex("ListingId");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("InsideAirBnBV5.Models.SummaryListings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("Availability365");

                    b.Property<int?>("CalculatedHostListingsCount");

                    b.Property<int>("HostId");

                    b.Property<string>("HostName");

                    b.Property<DateTime?>("LastReview");

                    b.Property<double?>("Latitude");

                    b.Property<double?>("Longitude");

                    b.Property<int?>("MinimumNights");

                    b.Property<string>("Name");

                    b.Property<string>("Neighbourhood");

                    b.Property<string>("NeighbourhoodGroup");

                    b.Property<int?>("NumberOfReviews");

                    b.Property<int?>("Price");

                    b.Property<double?>("ReviewsPerMonth");

                    b.Property<string>("RoomType");

                    b.HasKey("Id");

                    b.ToTable("SummaryListings");
                });

            modelBuilder.Entity("InsideAirBnBV5.Models.SummaryReviews", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Date");

                    b.Property<int>("ListingId");

                    b.HasKey("Id");

                    b.ToTable("SummaryReviews");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Name")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("RoleId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id");

                    b.Property<int>("AccessFailedCount");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Email")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed");

                    b.Property<bool>("LockoutEnabled");

                    b.Property<DateTimeOffset?>("LockoutEnd");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash");

                    b.Property<string>("PhoneNumber");

                    b.Property<bool>("PhoneNumberConfirmed");

                    b.Property<string>("SecurityStamp");

                    b.Property<bool>("TwoFactorEnabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128);

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128);

                    b.Property<string>("ProviderDisplayName");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("RoleId");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128);

                    b.Property<string>("Name")
                        .HasMaxLength(128);

                    b.Property<string>("Value");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("InsideAirBnBV5.Models.Calendar", b =>
                {
                    b.HasOne("InsideAirBnBV5.Models.Listings", "Listing")
                        .WithMany("Calendar")
                        .HasForeignKey("ListingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("InsideAirBnBV5.Models.Reviews", b =>
                {
                    b.HasOne("InsideAirBnBV5.Models.Listings", "Listing")
                        .WithMany("Reviews")
                        .HasForeignKey("ListingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
