// <auto-generated />
using System;
using InsideAirbnb.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace InsideAirbnb.Migrations
{
    [DbContext(typeof(insideAirBnbV2Context))]
    partial class insideAirBnbV2ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0-preview5.19227.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("InsideAirbnb.Models.Calendar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Available")
                        .IsRequired()
                        .HasColumnName("available")
                        .HasMaxLength(50);

                    b.Property<DateTime>("Date")
                        .HasColumnName("date");

                    b.Property<int>("ListingId")
                        .HasColumnName("listing_id");

                    b.Property<string>("Price")
                        .HasColumnName("price")
                        .HasMaxLength(50);

                    b.Property<string>("TestString");

                    b.HasKey("Id");

                    b.HasIndex("ListingId");

                    b.ToTable("calendar");
                });

            modelBuilder.Entity("InsideAirbnb.Models.Listings", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnName("id");

                    b.Property<string>("Access")
                        .IsRequired()
                        .HasColumnName("access");

                    b.Property<int?>("Accommodates")
                        .HasColumnName("accommodates");

                    b.Property<string>("Amenities")
                        .HasColumnName("amenities");

                    b.Property<int?>("Availability30")
                        .HasColumnName("availability_30");

                    b.Property<int?>("Availability365")
                        .HasColumnName("availability_365");

                    b.Property<int?>("Availability60")
                        .HasColumnName("availability_60");

                    b.Property<int?>("Availability90")
                        .HasColumnName("availability_90");

                    b.Property<double?>("Bathrooms")
                        .HasColumnName("bathrooms");

                    b.Property<string>("BedType")
                        .HasColumnName("bed_type");

                    b.Property<int?>("Bedrooms")
                        .HasColumnName("bedrooms");

                    b.Property<int?>("Beds")
                        .HasColumnName("beds");

                    b.Property<int>("CalculatedHostListingsCount")
                        .HasColumnName("calculated_host_listings_count");

                    b.Property<DateTime?>("CalendarLastScraped")
                        .HasColumnName("calendar_last_scraped");

                    b.Property<string>("CalendarUpdated")
                        .HasColumnName("calendar_updated");

                    b.Property<string>("CancellationPolicy")
                        .IsRequired()
                        .HasColumnName("cancellation_policy");

                    b.Property<string>("City")
                        .HasColumnName("city");

                    b.Property<string>("CleaningFee")
                        .HasColumnName("cleaning_fee");

                    b.Property<string>("Country")
                        .HasColumnName("country");

                    b.Property<string>("CountryCode")
                        .HasColumnName("country_code");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnName("description");

                    b.Property<string>("ExperiencesOffered")
                        .IsRequired()
                        .HasColumnName("experiences_offered");

                    b.Property<string>("ExtraPeople")
                        .HasColumnName("extra_people");

                    b.Property<DateTime?>("FirstReview")
                        .HasColumnName("first_review");

                    b.Property<int?>("GuestsIncluded")
                        .HasColumnName("guests_included");

                    b.Property<string>("HasAvailability")
                        .HasColumnName("has_availability");

                    b.Property<string>("HostAbout")
                        .HasColumnName("host_about");

                    b.Property<string>("HostAcceptanceRate")
                        .HasColumnName("host_acceptance_rate");

                    b.Property<string>("HostHasProfilePic")
                        .HasColumnName("host_has_profile_pic");

                    b.Property<int>("HostId")
                        .HasColumnName("host_id");

                    b.Property<string>("HostIdentityVerified")
                        .HasColumnName("host_identity_verified");

                    b.Property<string>("HostIsSuperhost")
                        .HasColumnName("host_is_superhost");

                    b.Property<int?>("HostListingsCount")
                        .HasColumnName("host_listings_count");

                    b.Property<string>("HostLocation")
                        .HasColumnName("host_location");

                    b.Property<string>("HostName")
                        .HasColumnName("host_name");

                    b.Property<string>("HostNeighbourhood")
                        .HasColumnName("host_neighbourhood");

                    b.Property<string>("HostPictureUrl")
                        .HasColumnName("host_picture_url");

                    b.Property<string>("HostResponseRate")
                        .HasColumnName("host_response_rate");

                    b.Property<string>("HostResponseTime")
                        .HasColumnName("host_response_time");

                    b.Property<DateTime?>("HostSince")
                        .HasColumnName("host_since");

                    b.Property<string>("HostThumbnailUrl")
                        .HasColumnName("host_thumbnail_url");

                    b.Property<int?>("HostTotalListingsCount")
                        .HasColumnName("host_total_listings_count");

                    b.Property<string>("HostUrl")
                        .IsRequired()
                        .HasColumnName("host_url");

                    b.Property<string>("HostVerifications")
                        .HasColumnName("host_verifications");

                    b.Property<string>("HouseRules")
                        .IsRequired()
                        .HasColumnName("house_rules");

                    b.Property<string>("InstantBookable")
                        .IsRequired()
                        .HasColumnName("instant_bookable");

                    b.Property<string>("Interaction")
                        .IsRequired()
                        .HasColumnName("interaction");

                    b.Property<string>("IsBusinessTravelReady")
                        .IsRequired()
                        .HasColumnName("is_business_travel_ready");

                    b.Property<string>("IsLocationExact")
                        .HasColumnName("is_location_exact");

                    b.Property<string>("JurisdictionNames")
                        .HasColumnName("jurisdiction_names");

                    b.Property<DateTime?>("LastReview")
                        .HasColumnName("last_review");

                    b.Property<DateTime>("LastScraped")
                        .HasColumnName("last_scraped");

                    b.Property<double?>("Latitude")
                        .HasColumnName("latitude");

                    b.Property<string>("ListingUrl")
                        .IsRequired()
                        .HasColumnName("listing_url");

                    b.Property<double?>("Longitude")
                        .HasColumnName("longitude");

                    b.Property<string>("Market")
                        .HasColumnName("market");

                    b.Property<int?>("MaximumNights")
                        .HasColumnName("maximum_nights");

                    b.Property<string>("MediumUrl")
                        .HasColumnName("medium_url");

                    b.Property<int?>("MinimumNights")
                        .HasColumnName("minimum_nights");

                    b.Property<string>("MonthlyPrice")
                        .HasColumnName("monthly_price");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnName("name");

                    b.Property<string>("NeighborhoodOverview")
                        .IsRequired()
                        .HasColumnName("neighborhood_overview");

                    b.Property<string>("Neighbourhood")
                        .HasColumnName("neighbourhood");

                    b.Property<string>("NeighbourhoodCleansed")
                        .HasColumnName("neighbourhood_cleansed");

                    b.Property<string>("NeighbourhoodGroupCleansed")
                        .HasColumnName("neighbourhood_group_cleansed");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnName("notes");

                    b.Property<int?>("NumberOfReviews")
                        .HasColumnName("number_of_reviews");

                    b.Property<string>("PictureUrl")
                        .IsRequired()
                        .HasColumnName("picture_url");

                    b.Property<string>("Price")
                        .HasColumnName("price");

                    b.Property<string>("PropertyType")
                        .HasColumnName("property_type");

                    b.Property<string>("RequireGuestPhoneVerification")
                        .IsRequired()
                        .HasColumnName("require_guest_phone_verification");

                    b.Property<string>("RequireGuestProfilePicture")
                        .IsRequired()
                        .HasColumnName("require_guest_profile_picture");

                    b.Property<string>("RequiresLicense")
                        .IsRequired()
                        .HasColumnName("requires_license");

                    b.Property<int?>("ReviewScoresAccuracy")
                        .HasColumnName("review_scores_accuracy");

                    b.Property<int?>("ReviewScoresCheckin")
                        .HasColumnName("review_scores_checkin");

                    b.Property<int?>("ReviewScoresCleanliness")
                        .HasColumnName("review_scores_cleanliness");

                    b.Property<int?>("ReviewScoresCommunication")
                        .HasColumnName("review_scores_communication");

                    b.Property<int?>("ReviewScoresLocation")
                        .HasColumnName("review_scores_location");

                    b.Property<int?>("ReviewScoresRating")
                        .HasColumnName("review_scores_rating");

                    b.Property<int?>("ReviewScoresValue")
                        .HasColumnName("review_scores_value");

                    b.Property<double?>("ReviewsPerMonth")
                        .HasColumnName("reviews_per_month");

                    b.Property<string>("RoomType")
                        .HasColumnName("room_type");

                    b.Property<double>("ScrapeId")
                        .HasColumnName("scrape_id");

                    b.Property<string>("SecurityDeposit")
                        .HasColumnName("security_deposit");

                    b.Property<string>("SmartLocation")
                        .HasColumnName("smart_location");

                    b.Property<string>("Space")
                        .IsRequired()
                        .HasColumnName("space");

                    b.Property<string>("SquareFeet")
                        .HasColumnName("square_feet");

                    b.Property<string>("State")
                        .HasColumnName("state");

                    b.Property<string>("Street")
                        .HasColumnName("street");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnName("summary");

                    b.Property<string>("ThumbnailUrl")
                        .HasColumnName("thumbnail_url");

                    b.Property<string>("Transit")
                        .IsRequired()
                        .HasColumnName("transit");

                    b.Property<string>("WeeklyPrice")
                        .HasColumnName("weekly_price");

                    b.Property<string>("XlPictureUrl")
                        .HasColumnName("xl_picture_url");

                    b.Property<string>("Zipcode")
                        .HasColumnName("zipcode");

                    b.HasKey("Id");

                    b.ToTable("listings");
                });

            modelBuilder.Entity("InsideAirbnb.Models.Neighbourhoods", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Neighbourhood")
                        .IsRequired()
                        .HasColumnName("neighbourhood")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("neighbourhoods");
                });

            modelBuilder.Entity("InsideAirbnb.Models.Reviews", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnName("id");

                    b.Property<string>("Comments")
                        .IsRequired()
                        .HasColumnName("comments");

                    b.Property<DateTime>("Date")
                        .HasColumnName("date");

                    b.Property<int>("ListingId")
                        .HasColumnName("listing_id");

                    b.Property<int>("ReviewerId")
                        .HasColumnName("reviewer_id");

                    b.Property<string>("ReviewerName")
                        .IsRequired()
                        .HasColumnName("reviewer_name")
                        .HasMaxLength(150);

                    b.HasKey("Id");

                    b.HasIndex("ListingId");

                    b.ToTable("reviews");
                });

            modelBuilder.Entity("InsideAirbnb.Models.SummaryListings", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnName("id");

                    b.Property<int?>("Availability365")
                        .HasColumnName("availability_365");

                    b.Property<int?>("CalculatedHostListingsCount")
                        .HasColumnName("calculated_host_listings_count");

                    b.Property<int>("HostId")
                        .HasColumnName("host_id");

                    b.Property<string>("HostName")
                        .HasColumnName("host_name");

                    b.Property<DateTime?>("LastReview")
                        .HasColumnName("last_review");

                    b.Property<double?>("Latitude")
                        .HasColumnName("latitude");

                    b.Property<double?>("Longitude")
                        .HasColumnName("longitude");

                    b.Property<int?>("MinimumNights")
                        .HasColumnName("minimum_nights");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnName("name");

                    b.Property<string>("Neighbourhood")
                        .HasColumnName("neighbourhood");

                    b.Property<string>("NeighbourhoodGroup")
                        .HasColumnName("neighbourhood_group")
                        .HasMaxLength(1);

                    b.Property<int?>("NumberOfReviews")
                        .HasColumnName("number_of_reviews");

                    b.Property<int?>("Price")
                        .HasColumnName("price");

                    b.Property<double?>("ReviewsPerMonth")
                        .HasColumnName("reviews_per_month");

                    b.Property<string>("RoomType")
                        .HasColumnName("room_type");

                    b.HasKey("Id");

                    b.ToTable("summary-listings");
                });

            modelBuilder.Entity("InsideAirbnb.Models.SummaryReviews", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Date")
                        .HasColumnName("date");

                    b.Property<int>("ListingId")
                        .HasColumnName("listing_id");

                    b.HasKey("Id");

                    b.ToTable("summary-reviews");
                });

            modelBuilder.Entity("InsideAirbnb.Models.Calendar", b =>
                {
                    b.HasOne("InsideAirbnb.Models.Listings", "Listing")
                        .WithMany("Calendar")
                        .HasForeignKey("ListingId")
                        .HasConstraintName("FK_calendar_listings")
                        .IsRequired();
                });

            modelBuilder.Entity("InsideAirbnb.Models.Reviews", b =>
                {
                    b.HasOne("InsideAirbnb.Models.Listings", "Listing")
                        .WithMany("Reviews")
                        .HasForeignKey("ListingId")
                        .HasConstraintName("FK_reviews_listings")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
